import type { Category, DealType } from "./catalog";
import { countyLabel, FARM_COUNTY } from "./counties";

export type SeedListing = {
  slug: string;
  category: Category;
  dealType: DealType;
  title: string;
  summary: string;
  description: string;
  priceCents: number | null;
  priceLabel: string;
  quantity: string;
  location: string;
  region: string;
  farmName: string;
  farmNote: string;
  imagePath: string;
  tags: string;
  featured: boolean;
  daysAgo: number;
};

export type SeedNote = {
  listingSlug: string;
  farmName: string;
  body: string;
  hoursAgo: number;
};

const RAW_SEED_LISTINGS: SeedListing[] = [
  {
    slug: "alpine-does-cedar-hollow",
    category: "livestock",
    dealType: "sale",
    title: "Pair of Alpine dairy does",
    summary: "Two second-fresh Alpines, milking, used to the stanchion.",
    description:
      "Willow and Nettie, two registered-grade Alpine does, three and four years old. Both freshened in March and are milking about a gallon a day on pasture plus a little grain. Quiet at the stanchion, current on CDT, and used to being handled by kids. We downsized the dairy and they deserve a place that wants the milk. Can go as a pair only — they travel together.",
    priceCents: 75000,
    priceLabel: "$750 the pair",
    quantity: "2 does",
    location: "Cedar Hollow Farm",
    region: "Willow County, Iowa",
    farmName: "Cedar Hollow",
    farmNote: "Twelve acres of creek-bottom pasture, a small creamery, and too many projects.",
    imagePath: "/images/goats.jpg",
    tags: "goats,dairy,pair,alpine",
    featured: true,
    daysAgo: 1,
  },
  {
    slug: "jersey-heifer-evening-shade",
    category: "livestock",
    dealType: "sale",
    title: "Jersey heifer, springing",
    summary: "Fourteen months, due with a first calf in October.",
    description:
      "Buttercup is a quiet Jersey heifer, halter-broke and used to the parlor even though she hasn't calved yet. Bred to a calving-ease Jersey bull, due mid-October. She's on grass with the dry cows and comes when called. We kept her sister and don't have the stall. Health papers can travel with her.",
    priceCents: 145000,
    priceLabel: "$1,450",
    quantity: "1 heifer",
    location: "Evening Shade",
    region: "Hill Country, Texas",
    farmName: "Evening Shade",
    farmNote: "A small dairy on limestone hills. We sell cream and keep the calves.",
    imagePath: "/images/heifer.jpg",
    tags: "cattle,jersey,dairy,heifer",
    featured: true,
    daysAgo: 2,
  },
  {
    slug: "rhode-island-pullets",
    category: "livestock",
    dealType: "sale",
    title: "Heritage Rhode Island Red pullets",
    summary: "Twelve ready-to-lay birds, hatched here in February.",
    description:
      "A dozen pullets from our closed flock, just starting to color up. Raised on pasture in a tractor, no medications. They'll start laying in the next few weeks. Happy to sell the dozen or split into sixes. Crates welcome if you have them; otherwise I can lend mine for the drive.",
    priceCents: 21600,
    priceLabel: "$18 each",
    quantity: "12 pullets",
    location: "Swallowtail Homestead",
    region: "Driftless, Wisconsin",
    farmName: "Swallowtail",
    farmNote: "Orchard, layers, and a market garden on a south slope.",
    imagePath: "/images/chickens.jpg",
    tags: "chickens,layers,pullets,heritage",
    featured: false,
    daysAgo: 3,
  },
  {
    slug: "hampshire-piglets-for-hay",
    category: "livestock",
    dealType: "trade",
    title: "Hampshire piglets, trade for hay",
    summary: "Six weaned pigs. I'd rather stack bales than take cash.",
    description:
      "Last litter of the year, weaned last week and eating well on mash. Healthy, vaccinated, used to people in the pen. I'd like first-cut grass hay — square bales, dry, about a ton — more than I'd like the money. Open to a mix of hay and a little cash if that's what you've got.",
    priceCents: null,
    priceLabel: "Trade for hay",
    quantity: "6 piglets",
    location: "Red Gate Ranch",
    region: "Ozark foothills, Missouri",
    farmName: "Red Gate",
    farmNote: "Hogs, a few cows, and a fence that always needs work.",
    imagePath: "/images/piglets.jpg",
    tags: "pigs,trade,hay,weaners",
    featured: false,
    daysAgo: 4,
  },
  {
    slug: "nubian-doeling-wanted",
    category: "livestock",
    dealType: "seeking",
    title: "Looking for a Nubian doeling",
    summary: "Want one bottle baby or weaned kid to grow out with our doe.",
    description:
      "Our old Nubian is lonely after we lost her pen-mate. Looking for a doeling — bottle baby or just-weaned — with decent dairy lines if possible, but temperament matters more. Within a day's drive of the Finger Lakes. Can pick up this weekend.",
    priceCents: null,
    priceLabel: "Will pay fairly",
    quantity: "1 doeling",
    location: "Millcreek",
    region: "Finger Lakes, New York",
    farmName: "Millcreek",
    farmNote: "A hillside goat dairy and a farrier truck that covers two counties.",
    imagePath: "/images/nubian.jpg",
    tags: "goats,nubian,seeking,doeling",
    featured: false,
    daysAgo: 5,
  },
  {
    slug: "katahdin-ewes",
    category: "livestock",
    dealType: "sale",
    title: "Katahdin ewes, proven",
    summary: "Five hair sheep, easy keepers, lambed on grass.",
    description:
      "Downsizing the flock. Five Katahdin ewes, three to six years, all lambed this spring and weaned. No shearing, good mothers, used to electric netting. Can split the group if you only need two or three. Hoof trim done last month.",
    priceCents: 110000,
    priceLabel: "$220 / head",
    quantity: "5 ewes",
    location: "Two Pines",
    region: "Palouse, Washington",
    farmName: "Two Pines",
    farmNote: "Wheat on the ridges, sheep in the draws, orchard in the home forty.",
    imagePath: "/images/sheep.jpg",
    tags: "sheep,katahdin,ewes,hair",
    featured: true,
    daysAgo: 2,
  },
  {
    slug: "italian-bee-nucs",
    category: "livestock",
    dealType: "sale",
    title: "Overwintered Italian nucs",
    summary: "Five-frame nucs, laying queens, ready to build out.",
    description:
      "Four overwintered Italian nucs. Queens laying a solid pattern, plenty of stores, no mite issues this spring. Bring your own boxes or take mine with a deposit. Pickup only — I don't mail bees. First come, they're going fast.",
    priceCents: 18000,
    priceLabel: "$180 each",
    quantity: "4 nucs",
    location: "Fox Run",
    region: "Umpqua Valley, Oregon",
    farmName: "Fox Run",
    farmNote: "Bees, seed saving, and a wet spring garden.",
    imagePath: "/images/bees.jpg",
    tags: "bees,nucs,italian,honey",
    featured: false,
    daysAgo: 6,
  },
  {
    slug: "ford-3000-tractor",
    category: "equipment",
    dealType: "sale",
    title: "Ford 3000, 42 horse",
    summary: "1974 utility tractor. Starts, steers, and has new rear rubber.",
    description:
      "Our old chore tractor. Diesel, live PTO, eight-speed. Hours unknown — the meter quit in the nineties. New rear tires last fall, loader is not included (sold last year). It leaks a little from the rockshaft, as they do. Good for a small place. You haul, I help load.",
    priceCents: 420000,
    priceLabel: "$4,200",
    quantity: "1 tractor",
    location: "North Forty",
    region: "High Plains, Nebraska",
    farmName: "North Forty",
    farmNote: "Dryland grain, a shop that stays open late, and leftover posts from last year's fence.",
    imagePath: "/images/tractor.jpg",
    tags: "tractor,ford,diesel,utility",
    featured: true,
    daysAgo: 3,
  },
  {
    slug: "brush-hog-weekends",
    category: "equipment",
    dealType: "share",
    title: "Six-foot brush hog, weekends",
    summary: "Borrow the hog if you bring it back sharp and full of diesel.",
    description:
      "A 6-foot rotary cutter that lives on the three-point. I'm happy to lend it Saturday or Sunday as long as you have a tractor that can handle it (40 hp+) and you return it with the blades in decent shape. A couple gallons of diesel or a pie is plenty. Not for hire — neighbor use.",
    priceCents: null,
    priceLabel: "Borrow it",
    quantity: "1 implement",
    location: "Quarry Road",
    region: "Pine Ridge, Vermont",
    farmName: "Quarry Road",
    farmNote: "A woodlot, a few acres of hay, and a shed full of things we share.",
    imagePath: "/images/brushhog.jpg",
    tags: "brushhog,share,implement,mower",
    featured: false,
    daysAgo: 1,
  },
  {
    slug: "bcs-tiller",
    category: "equipment",
    dealType: "sale",
    title: "Walk-behind tiller, 30-inch",
    summary: "Two-wheel tractor with tiller. Honda engine, well kept.",
    description:
      "BCS-style walk-behind with a 30-inch tiller. Honda GX, recently serviced, new tines last season. We moved to a no-till bed system and it sits. Comes with the original manuals and a set of wheel weights. Pickup at the farm; I can help get it in a truck.",
    priceCents: 115000,
    priceLabel: "$1,150",
    quantity: "1 tiller",
    location: "Little Thistle",
    region: "Red Clay County, Tennessee",
    farmName: "Little Thistle",
    farmNote: "Market garden, a potting shed, and more tomatoes than we can can.",
    imagePath: "/images/tiller.jpg",
    tags: "tiller,bcs,garden,walk-behind",
    featured: false,
    daysAgo: 7,
  },
  {
    slug: "chicken-tractor-for-labor",
    category: "equipment",
    dealType: "trade",
    title: "Chicken tractor, trade for fencing",
    summary: "10×12 pasture coop. I'll trade it for a day of fence work.",
    description:
      "A stout 10-by-12 chicken tractor, cattle-panel frame, corrugated roof, wheels that actually roll. Held 30 layers last year. We built a permanent house and don't need two. Looking for a day's help stretching woven wire on the north line more than cash. Bring a come-along.",
    priceCents: null,
    priceLabel: "Trade for fencing labor",
    quantity: "1 coop",
    location: "Swallowtail Homestead",
    region: "Driftless, Wisconsin",
    farmName: "Swallowtail",
    farmNote: "Orchard, layers, and a market garden on a south slope.",
    imagePath: "/images/chicken-tractor.jpg",
    tags: "coop,trade,fencing,poultry",
    featured: false,
    daysAgo: 8,
  },
  {
    slug: "timothy-hay-bales",
    category: "materials",
    dealType: "sale",
    title: "First-cut timothy, square bales",
    summary: "Eighty dry bales left in the hay barn. No rain.",
    description:
      "First cutting, mid-June, never rained on. Tight squares, about 45 pounds. Stored off the ground in the hay barn. Good horse hay; we feed it to the goats too. $7 a bale or $6.50 if you take forty or more. Load your own, I'll run the elevator.",
    priceCents: 700,
    priceLabel: "$7 / bale",
    quantity: "80 bales",
    location: "Cedar Hollow Farm",
    region: "Willow County, Iowa",
    farmName: "Cedar Hollow",
    farmNote: "Twelve acres of creek-bottom pasture, a small creamery, and too many projects.",
    imagePath: "/images/hay.jpg",
    tags: "hay,timothy,bales,feed",
    featured: true,
    daysAgo: 0,
  },
  {
    slug: "cedar-fence-posts",
    category: "materials",
    dealType: "sale",
    title: "Cedar posts left from the west fence",
    summary: "Forty split-cedar posts, 7-foot, plus a roll of leftover wire.",
    description:
      "We over-ordered for the west line. Forty split cedar posts, seven foot, already pointed. Also one partial roll of 12.5 ga high-tensile. $8 a post, wire is free if you take twenty or more. They've been under cover.",
    priceCents: 800,
    priceLabel: "$8 / post",
    quantity: "40 posts",
    location: "North Forty",
    region: "High Plains, Nebraska",
    farmName: "North Forty",
    farmNote: "Dryland grain, a shop that stays open late, and leftover posts from last year's fence.",
    imagePath: "/images/posts.jpg",
    tags: "fence,posts,cedar,wire",
    featured: false,
    daysAgo: 4,
  },
  {
    slug: "tomato-and-sauce",
    category: "produce",
    dealType: "share",
    title: "Tomatoes and extra sauce",
    summary: "The beds went wild. Come fill a crate; sauce jars too.",
    description:
      "Romas and a few heirlooms still coming on. We canned until the pantry filled. Free to neighbors — bring your own crates or boxes. A case of pint sauce jars is also up for grabs if you'll use it this winter. Porch pickup, Saturday morning.",
    priceCents: null,
    priceLabel: "Free at the porch",
    quantity: "crates + jars",
    location: "Little Thistle",
    region: "Red Clay County, Tennessee",
    farmName: "Little Thistle",
    farmNote: "Market garden, a potting shed, and more tomatoes than we can can.",
    imagePath: "/images/produce.jpg",
    tags: "produce,tomatoes,canning,free",
    featured: false,
    daysAgo: 1,
  },
  {
    slug: "heirloom-seed-surplus",
    category: "materials",
    dealType: "trade",
    title: "Saved seed, looking to swap",
    summary: "Beans, squash, and a few tomatoes from last year's rows.",
    description:
      "I saved more than we'll plant. Dry beans (Jacob's Cattle and a local half-runner), two winter squashes, and a paste tomato that did well in the wet. Looking to trade for onion sets, garlic, or any grain you saved. Packets are labeled; meet at the potting bench.",
    priceCents: null,
    priceLabel: "Swap seed",
    quantity: "several packets",
    location: "Fox Run",
    region: "Umpqua Valley, Oregon",
    farmName: "Fox Run",
    farmNote: "Bees, seed saving, and a wet spring garden.",
    imagePath: "/images/seeds.jpg",
    tags: "seed,heirloom,trade,beans",
    featured: false,
    daysAgo: 9,
  },
  {
    slug: "seasoned-oak-firewood",
    category: "materials",
    dealType: "sale",
    title: "Seasoned oak, two cords extra",
    summary: "Split, stacked, two years dry. More than the woodshed holds.",
    description:
      "We cut heavy two winters ago. Two cords of oak, split and stacked by the woodshed, fully seasoned. $220 a cord, you load. Mix of round and split. Not delivering this month — the truck's in the shop — but I can help throw it in yours.",
    priceCents: 22000,
    priceLabel: "$220 / cord",
    quantity: "2 cords",
    location: "Quarry Road",
    region: "Pine Ridge, Vermont",
    farmName: "Quarry Road",
    farmNote: "A woodlot, a few acres of hay, and a shed full of things we share.",
    imagePath: "/images/firewood.jpg",
    tags: "firewood,oak,seasoned,heat",
    featured: false,
    daysAgo: 5,
  },
  {
    slug: "farrier-rounds",
    category: "skills",
    dealType: "offered",
    title: "Mobile farrier, forty-mile ring",
    summary: "Trims and shoes. I run a loop through the Finger Lakes.",
    description:
      "I shoe and trim Tuesdays through Fridays, forty miles from Millcreek. $55 a trim, $110 a set of shoes. I bring the anvil; you have a flat, quiet place to work and a horse that can stand. New clients: send a note with the animal's manners and your place. I keep a wait list in mud season.",
    priceCents: 5500,
    priceLabel: "$55 trim / $110 shoe",
    quantity: "by appointment",
    location: "Millcreek",
    region: "Finger Lakes, New York",
    farmName: "Millcreek",
    farmNote: "A hillside goat dairy and a farrier truck that covers two counties.",
    imagePath: "/images/farrier.jpg",
    tags: "farrier,horses,hoof,mobile",
    featured: true,
    daysAgo: 2,
  },
  {
    slug: "fence-crew-of-two",
    category: "skills",
    dealType: "offered",
    title: "Fence crew of two",
    summary: "Woven wire, high-tensile, wood. Day rate or trade for beef.",
    description:
      "My brother and I build fence. Woven wire, high-tensile, board, and repairs where the creek took a post. $28 an hour each, or we'll take a quarter of beef against a long job. We bring the stretchers and the post driver; you furnish materials. Book two weeks out.",
    priceCents: 2800,
    priceLabel: "$28 / hour each",
    quantity: "crew of 2",
    location: "Red Gate Ranch",
    region: "Ozark foothills, Missouri",
    farmName: "Red Gate",
    farmNote: "Hogs, a few cows, and a fence that always needs work.",
    imagePath: "/images/fencing.jpg",
    tags: "fence,labor,crew,wire",
    featured: true,
    daysAgo: 3,
  },
  {
    slug: "orchard-pruning",
    category: "skills",
    dealType: "offered",
    title: "Orchard pruning and grafting",
    summary: "Apples, pears, a few plums. Day rate, your trees.",
    description:
      "I prune dormant fruit trees and can graft scion if you have wood you like. Day rate $200, usually a dozen mature trees or a young orchard. Bring coffee. I trained in the Palouse and work from late February through bud break. Tools are mine; a ladder helps on the old standards.",
    priceCents: 20000,
    priceLabel: "$200 / day",
    quantity: "day rate",
    location: "Two Pines",
    region: "Palouse, Washington",
    farmName: "Two Pines",
    farmNote: "Wheat on the ridges, sheep in the draws, orchard in the home forty.",
    imagePath: "/images/orchard.jpg",
    tags: "pruning,orchard,grafting,trees",
    featured: false,
    daysAgo: 6,
  },
  {
    slug: "on-farm-tractor-repair",
    category: "skills",
    dealType: "offered",
    title: "On-farm small engine and tractor repair",
    summary: "I come to you. Diesels, mowers, the thing that won't start.",
    description:
      "Shop's on the place but I'll drive out if the machine won't. Tractors, tillers, chainsaws, pumps. I don't do automotive. Labor is $65 an hour plus parts at cost. Tell me what it is and what it did last in the note. Hill Country and a little beyond.",
    priceCents: 6500,
    priceLabel: "$65 / hour",
    quantity: "on-farm visits",
    location: "Evening Shade",
    region: "Hill Country, Texas",
    farmName: "Evening Shade",
    farmNote: "A small dairy on limestone hills. We sell cream and keep the calves.",
    imagePath: "/images/repair.jpg",
    tags: "repair,tractor,diesel,mechanic",
    featured: false,
    daysAgo: 4,
  },
  {
    slug: "cheesemaking-saturdays",
    category: "skills",
    dealType: "offered",
    title: "Cheesemaking, Saturday mornings",
    summary: "Farmhouse cheese in our creamery. Four seats, bring a pot.",
    description:
      "Once a month I teach a four-hour farmhouse cheese make in the creamery. Fresh mozzarella one month, a simple tomme the next. $40 covers milk and culture; you take home what we make. Four seats. Next date goes to the first notes on this listing. No experience needed — just clean hands and curiosity.",
    priceCents: 4000,
    priceLabel: "$40 / seat",
    quantity: "4 seats",
    location: "Cedar Hollow Farm",
    region: "Willow County, Iowa",
    farmName: "Cedar Hollow",
    farmNote: "Twelve acres of creek-bottom pasture, a small creamery, and too many projects.",
    imagePath: "/images/cheese.jpg",
    tags: "cheese,class,dairy,workshop",
    featured: false,
    daysAgo: 8,
  },
  {
    slug: "sweet-corn-and-squash",
    category: "produce",
    dealType: "sale",
    title: "Sweet corn and winter squash",
    summary: "Wagon's full. Corn this week, squash that'll keep.",
    description:
      "Last two plantings of sweet corn came on at once, plus a wagon of butternut and a long-keeping Hubbard. Corn is $5 a dozen, squash $3 each or a bushel for $20. Trade considered for eggs or onions. Porch pickup, evenings after chores.",
    priceCents: 500,
    priceLabel: "$5 / dozen corn",
    quantity: "wagon load",
    location: "Little Thistle",
    region: "Red Clay County, Tennessee",
    farmName: "Little Thistle",
    farmNote: "Market garden, a potting shed, and more tomatoes than we can can.",
    imagePath: "/images/corn-squash.jpg",
    tags: "corn,squash,produce,sale",
    featured: true,
    daysAgo: 1,
  },
  {
    slug: "farm-eggs-dozen",
    category: "produce",
    dealType: "trade",
    title: "Pasture eggs, open to trade",
    summary: "Two flats a week extra. Cash or trade for produce.",
    description:
      "The hens are laying harder than we can eat. $5 a dozen, or I'll trade for greens, onions, or a jar of something you put up. Unwashed if you want; otherwise wiped. Saturday morning at the potting shed.",
    priceCents: 500,
    priceLabel: "$5 / dozen or trade",
    quantity: "2 flats / week",
    location: "Swallowtail Homestead",
    region: "Driftless, Wisconsin",
    farmName: "Swallowtail",
    farmNote: "Orchard, layers, and a market garden on a south slope.",
    imagePath: "/images/eggs.jpg",
    tags: "eggs,trade,produce,layers",
    featured: false,
    daysAgo: 2,
  },
  {
    slug: "cattle-panels-free",
    category: "materials",
    dealType: "share",
    title: "Cattle panels and leftover wire",
    summary: "Free if you haul this week. Taking up the west wall of the shed.",
    description:
      "Eight 16-foot cattle panels and a partial roll of chicken wire from a coop we tore down. No holes worth mentioning. Free — I need the wall. Bring a truck with racks. First note gets them.",
    priceCents: null,
    priceLabel: "Free if you haul",
    quantity: "8 panels + wire",
    location: "North Forty",
    region: "High Plains, Nebraska",
    farmName: "North Forty",
    farmNote: "Dryland grain, a shop that stays open late, and leftover posts from last year's fence.",
    imagePath: "/images/panels.jpg",
    tags: "panels,wire,free,share",
    featured: true,
    daysAgo: 0,
  },
  {
    slug: "stock-tank-free",
    category: "equipment",
    dealType: "share",
    title: "Galvanized stock tank, free",
    summary: "300-gallon tank we don't need. Come get it.",
    description:
      "A sound 300-gallon galvanized tank. Held water all last summer, no pinholes I can find. We switched to a tire tank. Free to a neighbor who can lift it — two people, or a loader. Not delivering.",
    priceCents: null,
    priceLabel: "Free",
    quantity: "1 tank",
    location: "Evening Shade",
    region: "Hill Country, Texas",
    farmName: "Evening Shade",
    farmNote: "A small dairy on limestone hills. We sell cream and keep the calves.",
    imagePath: "/images/stock-tank.jpg",
    tags: "tank,water,free,share",
    featured: false,
    daysAgo: 3,
  },
  {
    slug: "forty-acres-cash-rent",
    category: "land",
    dealType: "lease",
    title: "40 acres cropland, cash rent",
    summary: "Tilled, tiled, and on a good road. One-year lease, option to renew.",
    description:
      "Forty acres of silt loam, tiled, last in beans. Looking for a clean renter for next season — $125 an acre, cash in spring. You plant, you keep the crop. I farm the home eighty and don't have the time. Soil test from last fall is in the shop. Walk it anytime.",
    priceCents: 12500,
    priceLabel: "$125 / acre",
    quantity: "40 acres",
    location: "Cedar Hollow Farm",
    region: "Willow County, Iowa",
    farmName: "Cedar Hollow",
    farmNote: "Twelve acres of creek-bottom pasture, a small creamery, and too many projects.",
    imagePath: "/images/cropland.jpg",
    tags: "land,lease,cropland,rent",
    featured: true,
    daysAgo: 2,
  },
  {
    slug: "pasture-lease-goats-cattle",
    category: "land",
    dealType: "lease",
    title: "12 acres pasture, goats or cattle",
    summary: "Fenced, water in, looking for someone to graze it.",
    description:
      "Twelve acres of mixed grass with a tank and a shade lot. Fence is woven wire on three sides, two-strand electric on the lane. $40 an acre for the season, or help me rebuild the north line and we'll call it even. No horses — the fence isn't built for it.",
    priceCents: 4000,
    priceLabel: "$40 / acre or fence trade",
    quantity: "12 acres",
    location: "Red Gate Ranch",
    region: "Ozark foothills, Missouri",
    farmName: "Red Gate",
    farmNote: "Hogs, a few cows, and a fence that always needs work.",
    imagePath: "/images/pasture.jpg",
    tags: "pasture,lease,grazing,goats",
    featured: false,
    daysAgo: 4,
  },
  {
    slug: "timber-deer-lease",
    category: "hunting",
    dealType: "lease",
    title: "80 acres timber, deer and turkey",
    summary: "Hardwood ridge and a field edge. Two hunters, season lease.",
    description:
      "Eighty acres of oak-hickory with a south field edge. Two hunters max, no ATVs off the lane, no night hunting. $1,200 the season, split if you bring a partner. Stands stay if they're safe; otherwise pack them out. I'll walk it with you at first light.",
    priceCents: 120000,
    priceLabel: "$1,200 / season",
    quantity: "80 acres, 2 hunters",
    location: "Red Gate Ranch",
    region: "Ozark foothills, Missouri",
    farmName: "Red Gate",
    farmNote: "Hogs, a few cows, and a fence that always needs work.",
    imagePath: "/images/hunting-woods.jpg",
    tags: "hunting,lease,deer,turkey",
    featured: true,
    daysAgo: 3,
  },
  {
    slug: "creek-bottom-hunting",
    category: "hunting",
    dealType: "lease",
    title: "Creek-bottom hunting lease",
    summary: "Forty acres of timber and a small food plot. Quiet place.",
    description:
      "Forty acres along a creek, a half-acre food plot I plant in clover, and a stand of old timber. One hunter. $800 the season. No baiting, no driving in past the gate after dark. Good for someone who wants to walk in. I farm around it and I don't hunt.",
    priceCents: 80000,
    priceLabel: "$800 / season",
    quantity: "40 acres, 1 hunter",
    location: "Quarry Road",
    region: "Pine Ridge, Vermont",
    farmName: "Quarry Road",
    farmNote: "A woodlot, a few acres of hay, and a shed full of things we share.",
    imagePath: "/images/hunting-creek.jpg",
    tags: "hunting,lease,creek,woods",
    featured: false,
    daysAgo: 6,
  },
];

export const SEED_LISTINGS: SeedListing[] = RAW_SEED_LISTINGS.map((item) => {
  const county = FARM_COUNTY[item.farmName] ?? "Richland";
  return { ...item, region: countyLabel(county) };
});

export const SEED_NOTES: SeedNote[] = [
  {
    listingSlug: "alpine-does-cedar-hollow",
    farmName: "Two Pines",
    body: "If the pair is still there Saturday I can trailer over from the west. We have a stanchion ready.",
    hoursAgo: 11,
  },
  {
    listingSlug: "timothy-hay-bales",
    farmName: "Red Gate",
    body: "I'll take forty bales if you can load Friday after chores. Cash in hand.",
    hoursAgo: 5,
  },
  {
    listingSlug: "brush-hog-weekends",
    farmName: "Fox Run",
    body: "Need it this Sunday to knock down the ditch. 45-horse tractor. I'll fill the tank.",
    hoursAgo: 20,
  },
  {
    listingSlug: "farrier-rounds",
    farmName: "Quarry Road",
    body: "Two horses that stand well. Next Tuesday afternoon if you're on that loop.",
    hoursAgo: 8,
  },
  {
    listingSlug: "ford-3000-tractor",
    farmName: "Little Thistle",
    body: "Is the loader bracket still on it, or was that sold with the loader?",
    hoursAgo: 30,
  },
  {
    listingSlug: "cattle-panels-free",
    farmName: "Swallowtail",
    body: "I can take the panels Thursday if they're still against the wall. Truck with racks.",
    hoursAgo: 4,
  },
  {
    listingSlug: "forty-acres-cash-rent",
    farmName: "North Forty",
    body: "I'd like to walk it this week. Beans last year — what's the lime history?",
    hoursAgo: 16,
  },
  {
    listingSlug: "timber-deer-lease",
    farmName: "Millcreek",
    body: "Two of us, both sit still. Can we look at it opening weekend of October?",
    hoursAgo: 9,
  },
];
