/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AgreeRouteImport } from './routes/agree'
import { Route as ImproveRouteImport } from './routes/improve'
import { Route as InvitesRouteImport } from './routes/invites'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LeasesRouteImport } from './routes/leases'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketRouteImport } from './routes/market'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NeedsRouteImport } from './routes/needs'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as PostRouteImport } from './routes/post'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ShareRouteImport } from './routes/share'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as ListingSlugRouteImport } from './routes/listing.$slug'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreeRoute = AgreeRouteImport.update({
  id: '/agree',
  path: '/agree',
  getParentRoute: () => rootRouteImport,
} as any)
const ImproveRoute = ImproveRouteImport.update({
  id: '/improve',
  path: '/improve',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitesRoute = InvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LeasesRoute = LeasesRouteImport.update({
  id: '/leases',
  path: '/leases',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedsRoute = NeedsRouteImport.update({
  id: '/needs',
  path: '/needs',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LearnRoute,
} as any)
const ListingSlugRoute = ListingSlugRouteImport.update({
  id: '/listing/$slug',
  path: '/listing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agree': typeof AgreeRoute
  '/improve': typeof ImproveRoute
  '/invites': typeof InvitesRoute
  '/learn': typeof LearnRouteWithChildren
  '/leases': typeof LeasesRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/messages': typeof MessagesRoute
  '/needs': typeof NeedsRoute
  '/office': typeof OfficeRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/share': typeof ShareRoute
  '/skills': typeof SkillsRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/listing/$slug': typeof ListingSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/learn/': typeof LearnIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agree': typeof AgreeRoute
  '/improve': typeof ImproveRoute
  '/invites': typeof InvitesRoute
  '/leases': typeof LeasesRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/messages': typeof MessagesRoute
  '/needs': typeof NeedsRoute
  '/office': typeof OfficeRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/share': typeof ShareRoute
  '/skills': typeof SkillsRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/listing/$slug': typeof ListingSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/learn': typeof LearnIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agree': typeof AgreeRoute
  '/improve': typeof ImproveRoute
  '/invites': typeof InvitesRoute
  '/learn': typeof LearnRouteWithChildren
  '/leases': typeof LeasesRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/messages': typeof MessagesRoute
  '/needs': typeof NeedsRoute
  '/office': typeof OfficeRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/share': typeof ShareRoute
  '/skills': typeof SkillsRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/listing/$slug': typeof ListingSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/learn/': typeof LearnIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agree'
    | '/improve'
    | '/invites'
    | '/learn'
    | '/leases'
    | '/listings'
    | '/login'
    | '/market'
    | '/messages'
    | '/needs'
    | '/office'
    | '/post'
    | '/profile'
    | '/saved'
    | '/share'
    | '/skills'
    | '/learn/$slug'
    | '/listing/$slug'
    | '/u/$username'
    | '/learn/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agree'
    | '/improve'
    | '/invites'
    | '/leases'
    | '/listings'
    | '/login'
    | '/market'
    | '/messages'
    | '/needs'
    | '/office'
    | '/post'
    | '/profile'
    | '/saved'
    | '/share'
    | '/skills'
    | '/learn/$slug'
    | '/listing/$slug'
    | '/u/$username'
    | '/learn'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agree'
    | '/improve'
    | '/invites'
    | '/learn'
    | '/leases'
    | '/listings'
    | '/login'
    | '/market'
    | '/messages'
    | '/needs'
    | '/office'
    | '/post'
    | '/profile'
    | '/saved'
    | '/share'
    | '/skills'
    | '/learn/$slug'
    | '/listing/$slug'
    | '/u/$username'
    | '/learn/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgreeRoute: typeof AgreeRoute
  ImproveRoute: typeof ImproveRoute
  InvitesRoute: typeof InvitesRoute
  LearnRoute: typeof LearnRouteWithChildren
  LeasesRoute: typeof LeasesRoute
  ListingsRoute: typeof ListingsRoute
  LoginRoute: typeof LoginRoute
  MarketRoute: typeof MarketRoute
  MessagesRoute: typeof MessagesRoute
  NeedsRoute: typeof NeedsRoute
  OfficeRoute: typeof OfficeRoute
  PostRoute: typeof PostRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  ShareRoute: typeof ShareRoute
  SkillsRoute: typeof SkillsRoute
  ListingSlugRoute: typeof ListingSlugRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agree': {
      id: '/agree'
      path: '/agree'
      fullPath: '/agree'
      preLoaderRoute: typeof AgreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/improve': {
      id: '/improve'
      path: '/improve'
      fullPath: '/improve'
      preLoaderRoute: typeof ImproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invites': {
      id: '/invites'
      path: '/invites'
      fullPath: '/invites'
      preLoaderRoute: typeof InvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leases': {
      id: '/leases'
      path: '/leases'
      fullPath: '/leases'
      preLoaderRoute: typeof LeasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/needs': {
      id: '/needs'
      path: '/needs'
      fullPath: '/needs'
      preLoaderRoute: typeof NeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof LearnRoute
    }
    '/listing/$slug': {
      id: '/listing/$slug'
      path: '/listing/$slug'
      fullPath: '/listing/$slug'
      preLoaderRoute: typeof ListingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LearnRouteChildren {
  LearnSlugRoute: typeof LearnSlugRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnSlugRoute: LearnSlugRoute,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgreeRoute: AgreeRoute,
  ImproveRoute: ImproveRoute,
  InvitesRoute: InvitesRoute,
  LearnRoute: LearnRouteWithChildren,
  LeasesRoute: LeasesRoute,
  ListingsRoute: ListingsRoute,
  LoginRoute: LoginRoute,
  MarketRoute: MarketRoute,
  MessagesRoute: MessagesRoute,
  NeedsRoute: NeedsRoute,
  OfficeRoute: OfficeRoute,
  PostRoute: PostRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  ShareRoute: ShareRoute,
  SkillsRoute: SkillsRoute,
  ListingSlugRoute: ListingSlugRoute,
  UUsernameRoute: UUsernameRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
